import { sql } from "drizzle-orm";
import { buyerRequestsTable, db } from "@workspace/db";

const sampleRequests = [
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e01",
    title: "Commercial Cleaning Business — South Florida",
    industry: "Business Services",
    businessCategory: "Commercial cleaning",
    buyerType: "search_fund",
    country: "United States",
    region: "Florida",
    city: "Miami",
    radiusMiles: 150,
    remoteAccepted: false,
    minimumPurchasePrice: 650000,
    maximumPurchasePrice: 2000000,
    minimumRevenue: 1000000,
    minimumEbitda: 225000,
    minimumCashFlow: 175000,
    preferredProfile:
      "Target revenue of $1.0M+ and adjusted EBITDA of at least $225K. Seeking recurring commercial cleaning contracts across South Florida, diversified customers, documented renewals, and a trained supervisor team.",
    dealExclusions:
      "Residential-only operators; any customer above 25% of revenue; contracts without renewal history; unresolved labor or licensing issues.",
    timeline: "3–6 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 2.0%–3.0% of final transaction value (approximately $13,000–$60,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e02",
    title: "HVAC & Plumbing Company — Florida",
    industry: "Home Services",
    businessCategory: "HVAC and plumbing",
    buyerType: "individual",
    country: "United States",
    region: "Florida",
    city: "Orlando",
    radiusMiles: 150,
    remoteAccepted: false,
    minimumPurchasePrice: 1500000,
    maximumPurchasePrice: 6000000,
    minimumRevenue: 2000000,
    minimumEbitda: 400000,
    minimumCashFlow: 300000,
    preferredProfile:
      "Target revenue of $2.0M+ and adjusted EBITDA of at least $400K. Florida HVAC and plumbing operator with licensed technicians, recurring maintenance agreements, a balanced service and replacement mix, and a manager able to support a transition.",
    dealExclusions:
      "New-construction-only contractors; businesses dependent on one licensed individual; unresolved code, warranty, or environmental matters; excessive customer concentration.",
    timeline: "3–6 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 1.5%–2.5% of final transaction value (approximately $22,500–$150,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e03",
    title: "Beauty / Skincare E-commerce Brand — United States",
    industry: "Consumer & E-commerce",
    businessCategory: "Beauty and skincare e-commerce",
    buyerType: "search_fund",
    country: "United States",
    region: null,
    city: null,
    radiusMiles: null,
    remoteAccepted: true,
    minimumPurchasePrice: 1000000,
    maximumPurchasePrice: 7000000,
    minimumRevenue: 2500000,
    minimumEbitda: 500000,
    minimumCashFlow: 350000,
    preferredProfile:
      "Target revenue of $2.5M+ and adjusted EBITDA of at least $500K. U.S.-based brand with repeat purchase behavior, healthy gross margins, diversified customer acquisition, owned customer data, and room to expand into retail or wholesale.",
    dealExclusions:
      "Unproven or single-product brands; material regulatory or product-safety concerns; more than 60% of new customers from one paid channel; unverifiable supplier or inventory records.",
    timeline: "3–9 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 1.5%–2.5% of final transaction value (approximately $15,000–$175,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e04",
    title: "Logistics / 3PL Company — Texas",
    industry: "Transportation & Logistics",
    businessCategory: "Third-party logistics and warehousing",
    buyerType: "private_equity",
    country: "United States",
    region: "Texas",
    city: "Dallas",
    radiusMiles: 250,
    remoteAccepted: false,
    minimumPurchasePrice: 3000000,
    maximumPurchasePrice: 15000000,
    minimumRevenue: 5000000,
    minimumEbitda: 750000,
    minimumCashFlow: 550000,
    preferredProfile:
      "Target revenue of $5.0M+ and adjusted EBITDA of at least $750K. Texas-based 3PL with repeat shipper accounts, reliable warehouse operations, experienced dispatch and operations leadership, and opportunities to add capacity.",
    dealExclusions:
      "Any customer above 30% of revenue; distressed fleets or facilities with unresolved environmental liabilities; contracts that cannot be assigned; businesses with incomplete safety records.",
    timeline: "6–12 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 1.0%–2.0% of final transaction value (approximately $30,000–$300,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e05",
    title: "Home Services Company — Atlanta",
    industry: "Home Services",
    businessCategory: "Residential home services",
    buyerType: "individual",
    country: "United States",
    region: "Georgia",
    city: "Atlanta",
    radiusMiles: 125,
    remoteAccepted: false,
    minimumPurchasePrice: 700000,
    maximumPurchasePrice: 3000000,
    minimumRevenue: 1200000,
    minimumEbitda: 300000,
    minimumCashFlow: 225000,
    preferredProfile:
      "Target revenue of $1.2M+ and adjusted EBITDA of at least $300K. Atlanta-area service business with repeat customers, strong local reviews, a stable field crew, documented processes, and limited founder dependence.",
    dealExclusions:
      "Project-only operators with no repeat base; franchises with non-transferable agreements; unresolved licensing, safety, or tax issues; revenue materially dependent on the owner.",
    timeline: "3–6 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 2.0%–3.0% of final transaction value (approximately $14,000–$90,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e06",
    title: "Light Manufacturing Business — Texas / Florida",
    industry: "Manufacturing",
    businessCategory: "Light industrial manufacturing",
    buyerType: "strategic",
    country: "United States",
    region: "Texas / Florida",
    city: null,
    radiusMiles: null,
    remoteAccepted: false,
    minimumPurchasePrice: 2000000,
    maximumPurchasePrice: 12000000,
    minimumRevenue: 4000000,
    minimumEbitda: 600000,
    minimumCashFlow: 450000,
    preferredProfile:
      "Target revenue of $4.0M+ and adjusted EBITDA of at least $600K. Light manufacturer with repeat B2B customers, documented quality systems, well-maintained equipment, a capable plant manager, and operations in or near Texas or Florida.",
    dealExclusions:
      "Single-customer dependency above 30%; obsolete or unserviceable equipment; unresolved environmental or workplace-safety issues; businesses with no transition plan for key operators.",
    timeline: "6–12 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 1.0%–1.75% of final transaction value (approximately $20,000–$210,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e07",
    title: "Independent Boutique Hotel — Florida",
    industry: "Hospitality",
    businessCategory: "Independent boutique hotel",
    buyerType: "strategic",
    country: "United States",
    region: "Florida",
    city: "St. Augustine",
    radiusMiles: 150,
    remoteAccepted: false,
    minimumPurchasePrice: 3000000,
    maximumPurchasePrice: 18000000,
    minimumRevenue: 2500000,
    minimumEbitda: 500000,
    minimumCashFlow: 375000,
    preferredProfile:
      "Target revenue of $2.5M+ and adjusted EBITDA of at least $500K. Independent Florida hotel with a distinctive guest experience, consistent occupancy, capable on-site leadership, maintained facilities, and potential to improve direct bookings.",
    dealExclusions:
      "Franchise-only assets; deferred maintenance without a funded plan; unresolved title, zoning, or life-safety matters; properties whose reported revenue includes unrelated real estate activity.",
    timeline: "6–12 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 0.75%–1.5% of final transaction value (approximately $22,500–$270,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e08",
    title: "Dental Practice Group — South Florida",
    industry: "Healthcare",
    businessCategory: "Dental practice group",
    buyerType: "strategic",
    country: "United States",
    region: "Florida",
    city: "Fort Lauderdale",
    radiusMiles: 100,
    remoteAccepted: false,
    minimumPurchasePrice: 2000000,
    maximumPurchasePrice: 12000000,
    minimumRevenue: 2500000,
    minimumEbitda: 500000,
    minimumCashFlow: 375000,
    preferredProfile:
      "Target revenue of $2.5M+ and adjusted EBITDA of at least $500K. South Florida group with multiple providers or locations, stable patient retention, documented compliance, modern equipment, and a practical transition plan for clinicians.",
    dealExclusions:
      "Practices dependent on one departing dentist; unresolved licensing, payer, or patient-record compliance issues; material deferred equipment needs; unsupported add-backs.",
    timeline: "3–9 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 0.75%–1.5% of final transaction value (approximately $15,000–$180,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e09",
    title: "Auto Repair / Collision Center — Florida",
    industry: "Automotive",
    businessCategory: "Auto repair and collision center",
    buyerType: "individual",
    country: "United States",
    region: "Florida",
    city: "Jacksonville",
    radiusMiles: 150,
    remoteAccepted: false,
    minimumPurchasePrice: 500000,
    maximumPurchasePrice: 4000000,
    minimumRevenue: 1200000,
    minimumEbitda: 250000,
    minimumCashFlow: 185000,
    preferredProfile:
      "Target revenue of $1.2M+ and adjusted EBITDA of at least $250K. Florida shop with repeat local customers, experienced technicians, diversified repair and collision work, transferable insurer relationships, and organized service records.",
    dealExclusions:
      "Unresolved environmental or hazardous-material issues; salvage-only operations; non-transferable leases; material dependence on one insurer or fleet account.",
    timeline: "3–6 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 2.5%–3.5% of final transaction value (approximately $12,500–$140,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
  {
    id: "8b8dd350-43d1-4d4c-9f77-9bc6628f8e10",
    title: "Property Management Company — Southeast United States",
    industry: "Real Estate Services",
    businessCategory: "Property management",
    buyerType: "search_fund",
    country: "United States",
    region: "Southeast United States",
    city: null,
    radiusMiles: null,
    remoteAccepted: true,
    minimumPurchasePrice: 1500000,
    maximumPurchasePrice: 10000000,
    minimumRevenue: 2000000,
    minimumEbitda: 400000,
    minimumCashFlow: 300000,
    preferredProfile:
      "Target management-fee revenue of $2.0M+ and adjusted EBITDA of at least $400K. Southeast-focused operator with recurring contracts, a diversified owner and property base, low client churn, experienced regional managers, and documented systems.",
    dealExclusions:
      "Revenue that conflates management fees with property-owner rents; any client above 25% of fees; unresolved trust-account or licensing issues; contracts with non-transferable change-of-control terms.",
    timeline: "6–12 months",
    rewardDisclosure:
      "SAMPLE ONLY — Illustrative finder fee of 1.0%–2.0% of final transaction value (approximately $15,000–$200,000 across the stated purchase range). No fee is offered or guaranteed; any compensation requires a separate written agreement and remains subject to eligibility, licensing, and applicable law.",
  },
].map((request, index) => ({
  ...request,
  privacy: "public",
  isVerified: false,
  isExample: true,
  createdBy: "sample-buyer-request-seed",
  createdAt: new Date(Date.now() - index * 60_000),
})) satisfies (typeof buyerRequestsTable.$inferInsert)[];

export async function seedSampleBuyerRequests(): Promise<void> {
  await db
    .insert(buyerRequestsTable)
    .values(sampleRequests)
    .onConflictDoUpdate({
      target: buyerRequestsTable.id,
      set: {
        title: sql`excluded.title`,
        industry: sql`excluded.industry`,
        businessCategory: sql`excluded.business_category`,
        buyerType: sql`excluded.buyer_type`,
        country: sql`excluded.country`,
        region: sql`excluded.region`,
        city: sql`excluded.city`,
        radiusMiles: sql`excluded.radius_miles`,
        remoteAccepted: sql`excluded.remote_accepted`,
        minimumPurchasePrice: sql`excluded.minimum_purchase_price`,
        maximumPurchasePrice: sql`excluded.maximum_purchase_price`,
        minimumRevenue: sql`excluded.minimum_revenue`,
        minimumEbitda: sql`excluded.minimum_ebitda`,
        minimumCashFlow: sql`excluded.minimum_cash_flow`,
        preferredProfile: sql`excluded.preferred_profile`,
        dealExclusions: sql`excluded.deal_exclusions`,
        timeline: sql`excluded.timeline`,
        rewardDisclosure: sql`excluded.reward_disclosure`,
        privacy: sql`excluded.privacy`,
        isVerified: sql`excluded.is_verified`,
        isExample: sql`excluded.is_example`,
        createdAt: sql`excluded.created_at`,
      },
    });
}